version: "3.7"
services:
  app:
    container_name: exercise-tracker-app
    restart: always
    build: .
    environment:
      - MLAB_URI=mongodb://mongodb:27017/ExerciseTracker
      - NODE_ENV=DEV
    ports:
      - "8000:3000"
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
